-- 코드를 작성해주세요
SELECT 
    COUNT(I.ID) AS FISH_COUNT, NI.FISH_NAME AS FISH_NAME
FROM FISH_INFO I
JOIN FISH_NAME_INFO NI ON NI.FISH_TYPE = I.FISH_TYPE
GROUP BY NI.FISH_TYPE, NI.FISH_NAME
ORDER BY FISH_COUNT DESC;